---
- hosts: xds
  connection: local
  name: version 1.0 Fetches the AFUT supported Cray XD servers System Firmware Inventory Details along with Model name
  gather_facts: yes
  vars:
    bmc_username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=hsys-secrets/data/torch/ipmi:username', auth_method='jwt', mount_point='kubernetes', role_id='aap', jwt=jwt) }}"
    bmc_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=hsys-secrets/data/torch/ipmi:username', auth_method='jwt', mount_point='kubernetes', role_id='aap', jwt=jwt) }}"
    ansible_hashi_vault_url: 'https://vault.hpc.nyu.edu'
    ansible_hashi_vault_validate_certs: false
    baseuri: "{{ inventory_hostname }}"
    datatype: FirmwareInventory

  tasks:
    - name: Get Vault SA token
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: cicd
        namespace: u-workbench-cte3
      register: cicd
      no_log: "{{ log_debug | default(true) }}"
      delegate_to: 127.0.0.1
      become: false
      tags: always
    - name: Set JWT variable
      ansible.builtin.set_fact:
        jwt: "{{ cicd.resources[0].data.token | b64decode }}"
      no_log: "{{ log_debug | default(true) }}"
      become: false
      tags: always

    - name: System firmware Inventory Details will be stored in the below csv file
      set_fact:
        output_file: "All_System_FW_Inventory_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.csv"
      run_once: True

    - name: Fetching Inventory Details
      get_system_fw_inv:
        category: GetInventory
        command: GetSystemFWInventory
        baseuri: "{{ baseuri }}"
        username: "{{ bmc_username }}"
        password: "{{ bmc_password }}"
        output_file_name: "{{output_file}}"
      register: inv_output

    - name: Show formatted firmware inventory
      debug:
        var: inv_output

    # - name: Writing inventory details to {{output_file}} file
    #   shell: echo {{inv_output.msg}} >> {{output_file}}
