---
- hosts: xds
  gather_facts: yes
  connection: local
  name: version 1.0 System Firmware Update for HPE Cray XD670 systems
  
  vars:
    bmc_username: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=hsys-secrets/data/torch/ipmi:username', auth_method='jwt', mount_point='kubernetes', role_id='aap', jwt=jwt) }}"
    bmc_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=hsys-secrets/data/torch/ipmi:password', auth_method='jwt', mount_point='kubernetes', role_id='aap', jwt=jwt) }}"
    ansible_hashi_vault_url: 'https://vault.hpc.nyu.edu'
    ansible_hashi_vault_validate_certs: false
    baseuri: "{{ ansible_host }}"
 
  tasks:   
    - name: Get Vault SA token
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Secret
        name: cicd
        namespace: u-workbench-cte3
      register: cicd
      no_log: "{{ log_debug | default(true) }}"
      delegate_to: 127.0.0.1
      become: false
      tags: always
    - name: Set JWT variable
      ansible.builtin.set_fact:
        jwt: "{{ cicd.resources[0].data.token | b64decode }}"
      no_log: "{{ log_debug | default(true) }}"
      become: false
      tags: always
    
    - name: Fetch firmware files
      ansible.builtin.get_url:
        url: https://files-webserver-hpc-infra.apps.cloud.rt.nyu.edu/software/hpe/xd670/2025.08.00/2025.08.00.zip
        dest: "/var/tmp/firmware/"
        validate_certs: false
      
    - name: Unzip all compute firmware HPM files
      ansible.builtin.unarchive:
        src: "/var/tmp/firmware/2025.08.00.zip"
        dest: "/var/tmp/firmware/"

    - name: System Firmware Update Status result will be uploaded to the below csv file
      set_fact: 
        output_file: "System_FW_Update_{{ ansible_date_time.date }}_{{ ansible_date_time.time }}.csv"
      run_once: True
   
    - name: Running Firmware Update for Cray XD Servers
      update_system_firmware:
        category: Update
        command: SystemFirmwareUpdate
        baseuri: "{{ baseuri }}"
        username: "{{ bmc_username }}"
        password: "{{ bmc_password }}"
        output_file_name: "{{ output_file }}"
      register: system_fw_update_output

    - name: Read firmware update CSV file
      delegate_to: localhost
      run_once: true
      slurp:
        src: "{{ output_file }}"
      register: csv_data

    - name: Show CSV results in job output
      debug:
        msg: "{{ csv_data.content | b64decode }}"
    
    # - name: Writing Firmware Upgrade status details to {{output_file}} file
    #   shell: echo {{system_fw_update_output.msg}} >> {{ output_file }}
